version: "3.9"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  backend:
    build:
      dockerfile: Dockerfile
      context: ./backend
    command: >
      sh -c "python manage.py migrate &&
             python manage.py populate_data
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - db

  frontend:
    build:
      dockerfile: Dockerfile
      context: ./frontend
    command: node_modules/.bin/ng serve --host 0.0.0.0 --disableHostCheck --poll 1000 -o
    volumes:
      - ./frontend:/usr/bookForum/
      - '/usr/bookForum/node_modules'
    restart: always
    ports:
      - "4200:4200"
    depends_on:
      - backend