# Generated by Django 3.2.8 on 2021-10-11 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='published_year',
            field=models.PositiveSmallIntegerField(default=1984),
        ),
        migrations.AlterField(
            model_name='book',
            name='thumbnail',
            field=models.URLField(max_length=500),
        ),
        migrations.AlterField(
            model_name='genre',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
