# Generated by Django 3.2.8 on 2021-10-16 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20211016_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='book_id',
            new_name='book',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
